-- Generated by Matugen - Do not edit manually

local colors = {
    primary = "#d1bcfdff",
    primary_container = "#4e3d75ff",
    on_primary = "#37265cff",
    secondary = "#ccc2dbff",
    background = "#141218ff",
    surface = "#141218ff",
    outline = "#948f99ff",
    error = "#ffb4abff",
}

return colors
