-- Generated by Matugen - Do not edit manually

local colors = {
    primary = "#acc7ffff",
    primary_container = "#2a4678ff",
    on_primary = "#0e2f60ff",
    secondary = "#bec6dcff",
    background = "#111318ff",
    surface = "#111318ff",
    outline = "#8e9099ff",
    error = "#ffb4abff",
}

return colors
