-- Generated by Matugen - Do not edit manually

local colors = {
    primary = "#a3c9feff",
    primary_container = "#1e4876ff",
    on_primary = "#00315bff",
    secondary = "#bbc7dbff",
    background = "#111418ff",
    surface = "#111418ff",
    outline = "#8d9199ff",
    error = "#ffb4abff",
}

return colors
