require("animations.mine")

require("config.binds")
require("config.monitors")
require("config.autostart")
require("config.env")
require("config.appearance")
require("config.input")
require("config.gestures")
require("config.rules")
