format = """[╭─](dimmed white) $directory : $cmd_duration\
$line_break[╰─](dimmed white) $character\
"""

[character]
success_symbol = "[λ](orange)"
error_symbol = "[λ](red)"

[directory]
home_symbol = " "
read_only = " "
truncation_length = 6
truncation_symbol = " •••/"
format = "[$path](blue)"

[directory.substitutions]
"Desktop" = " "
"Documents" = " "
"Downloads" = " "
"Music" = "󰎈"
"Pictures" = " "
"Videos" = " "
"GitHub" = "󰊤 "

[cmd_duration]
min_time = 0
show_milliseconds = true
format = '[$duration](yellow)'
