-- Generated by Matugen - Do not edit manually

local colors = {
    primary = "#{{colors.primary.default.hex_stripped}}ff",
    primary_container = "#{{colors.primary_container.default.hex_stripped}}ff",
    on_primary = "#{{colors.on_primary.default.hex_stripped}}ff",
    secondary = "#{{colors.secondary.default.hex_stripped}}ff",
    background = "#{{colors.background.default.hex_stripped}}ff",
    surface = "#{{colors.surface.default.hex_stripped}}ff",
    outline = "#{{colors.outline.default.hex_stripped}}ff",
    error = "#{{colors.error.default.hex_stripped}}ff",
}

return colors
